[features]
seeds = false
skip-lint = false
[programs.devnet]
myprogram = "5sAeFvKkycHzV7DWMnLfZY8754CcKwWJiE885UxEooeX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
wallet = "/Users/michaelbychkowski/.config/solana/devnet.json"
cluster = "devnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
