[features]
seeds = false
skip-lint = false
[programs.devnet]
program_rust = "2yG52DZc3rExTmGRmiMShAGTQvkjrchBnFW5aPhzV37p"

[registry]
url = "https://solana-devnet.g.alchemy.com/v2/m2LeqehpNwV0M-_zyfc8JaNrb6lpWtU1"

[provider]
cluster = "devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
