[features]
seeds = false
skip-lint = false
[programs.localnet]
myepicproject = "2skVNsoum7EW7ocrznr4YnryBQP7zrBjSZGMpUDvrfPs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/michaelbychkowski/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
